### ISSUE TITLE
ReferenceError: move is not defined

### ISSUE THREAD

**Issue by Alek2077** [kolbytn/mindcraft#114]
Having some issues wtih the bot overall.
Example:
```Memory updated to: New Memory: Alex failed to write code when attempting to build a 5-tall dirt tower with a torch on top. Attempted to place dirt blocks manually using commands but mistakenly placed dirt at the same level multiple times. Encountered an error with a move command.
Received.
Full response: ""Looks like we're maxed out here. Moving up! !moveAway(2)""
parsed command: { commandName: '!moveAway', args: [ 2 ] }
executing code...

Code execution triggered catch: ReferenceError: move is not defined
Agent executed: !moveAway and got: Code output:
!!Code threw exception!! Error: ReferenceError: move is not defined

```

Since it says it's not defined, I suspect I have some outdated version of it? Or perhaps it could be some other issue?

GPT4o seems highly incompetent, as if there's some issue with the code, as if it's incomplete? Are we supposed to define these methods ourselves?

**Comment by Alek2077** [comment]
Looks like my issues were with not enabling the ability to inject code. This should be closed.

**Comment by kolbytn** [comment]
I think this should be fixed. Feel free to reopen if now.
