### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by riqvip** [kolbytn/mindcraft#122]
A while back I made a YouTube video on how to install. I didn't bother doing a pull request to add it to the README.me because I doubt it'd be merged. Here's the video though: https://youtu.be/engH5lQky6U

**Comment by kolbytn** [comment]
Thanks! You could post on the discord as well.

**Comment by riqvip** [comment]
> Thanks! You could post on the discord as well.

What discord? There's no link anywhere.
