### ISSUE TITLE
How can I disable "Aaa! A *Entity*"

### ISSUE THREAD

**Issue by Neko110923** [kolbytn/mindcraft#132]

**Comment by Neko110923** [comment]
I think it should be up to GPT to decide whether to run away or not

Or is there a way to give him control of himself?

**Comment by Neko110923** [comment]
Model: GPT4o_mini

I want him to attack zombies, but it seems like the system won't let him do that

**Comment by EIegance** [comment]
!setMode('cowardice', false)

**Comment by Neko110923** [comment]
it works , thank you!
