### ISSUE TITLE
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.

### ISSUE THREAD

**Issue by UnknKriod** [kolbytn/mindcraft#134]
I didn't change anything in the code.

**Comment by nikipi** [comment]
did you slove this? I have the same issue

**Comment by kolbytn** [comment]
This is a warning you will always get due to mineflayer. It does not indicate a problem with the bot.

**Comment by UnknKriod** [comment]
> This is a warning you will always get due to mineflayer. It does not indicate a problem with the bot.

Okay, then how do I ignore it? My bot doesn't start

**Comment by kolbytn** [comment]
If it doesn't start there's a different issue. Double check that you've follow the instructions for setup. Add your API key, turn on LAN mode to the correct port, etc... please open a new issue if you get a different error message.

**Comment by UnknKriod** [comment]
> If it doesn't start there's a different issue. Double check that you've follow the instructions for setup. Add your API key, turn on LAN mode to the correct port, etc... please open a new issue if you get a different error message.

Ok
