### ISSUE TITLE
gemini just don't do anything as it uses !newAction

### ISSUE THREAD

**Issue by hnrie** [kolbytn/mindcraft#137]
i said gemini to build a house so it use !newAction but, nothing happen

**Comment by kolbytn** [comment]
newAction only works if you've set `allow_insecure_coding` to true in settings.

**Comment by 5bridge** [comment]
I solved the problem with it with a simple change to the initial promt

**Comment by hnrie** [comment]
> newAction only works if you've set `allow_insecure_coding` to true in settings.

i did, but it still didn't work

**Comment by hnrie** [comment]
> I solved the problem with it with a simple change to the initial promt The problem is that it keeps trying to assign `!newAction` to non-existing arguments like this one:
> 
> ```
> parsed command: { commandName: '!newAction', args: [ 'buildHouse' ] }
> Agent executed: !newAction and got: Command !newAction was given 1 args, but requires 0 args.
> ```

oh that was my problem, also it got fixed, thxxx

**Comment by Shroototem** [comment]
`newAction` should be formatted like so `!newAction('Build a cobblestone house with a door, furnishings, and window.')` and the ai can learn it from within the profile json file. It's also not guaranteed that the specific model will understand.
```json
"conversation_examples": [
  [
    {"role": "user", "content": "poppy: build a cobblestone house"},
    {"role": "assistant", "content": "Sure. !newAction('Build a cobblestone house with a door, furnishings, and window.')"}
  ],
]
```

If this fixed the issue please make sure to close it. ❤️

**Comment by hnrie** [comment]
> `newAction` should be formatted like so `!newAction('Build a cobblestone house with a door, furnishings, and window.')` and the ai can learn it from within the profile json file. It's also not guaranteed that the specific model will understand.
> 
> ```json
> "conversation_examples": [
>   [
>     {"role": "user", "content": "poppy: build a cobblestone house"},
>     {"role": "assistant", "content": "Sure. !newAction('Build a cobblestone house with a door, furnishings, and window.')"}
>   ],
> ]
> ```
> 
> If this fixed the issue please make sure to close it. ❤️

ok thx
