### ISSUE TITLE
Question: What does "Allow insecure coding" do?

### ISSUE THREAD

**Issue by merll002** [kolbytn/mindcraft#141]

**Comment by ahmedjacop68** [comment]
it allows the AI to execute code on your computer to build houses and stuff

**Comment by merll002** [comment]
And if it were to be disabled? How would it do anything?

**Comment by ahmedjacop68** [comment]
It have some pre-written Scripts, and if you enable insecure coding be careful because AI might code some harmful stuff but most of the time it should be fine
