### ISSUE TITLE
Bot keeps wanting to attack dropped items

### ISSUE THREAD

**Issue by ShadeSilhouette** [kolbytn/mindcraft#146]
The version is 1.16.5, the bot keeps wanting to attack items and gets kicked half of the time with the error message "Bot kicked! {"translate":"multiplayer.disconnect.invalid_entity_attacked"}"

The bot runs away from items too if cowardice is set to true

**Comment by kolbytn** [comment]
Please use the Minecraft version mentioned in the readme. Mineflayer will not be compatible with all other versions.
