### ISSUE TITLE
Error: Profile not found, please restart your launcher - Microsoft Auth

### ISSUE THREAD

**Issue by samerfarida** [kolbytn/mindcraft#148]
I'm encountering the following error when attempting to run node main.js

"Error: Profile not found, please restart your launcher if you recently created your profile"

I am using microsoft as an auth method. I just recently crated a new email, and profile, it has been like this for a day. 

I am able to use the new email, and play Minecraft on my Mac Minecraft Launcher with issues. 

1. How can I maybe clear the microsoft auth creds so I can try again, because its cached somewhere? 
2. Or, how can I restart the repo launcher? 
3. Or, how can I fix this in general? 

<img width="1009" alt="Screenshot 2024-08-20 at 7 00 57 AM" src="https://github.com/user-attachments/assets/f267aa48-1961-452f-8dce-b059654fdf45">

**Comment by merll002** [comment]
Cant you just use offline mode?

**Comment by samerfarida** [comment]
I tired and it didnt allow me because my setup is kinda advanced here, running Minecraft server in multiplayer mode which doesnt allow local account/ offline mode. 

Anyway I was able to get it to work on a different computer. But the issue still on the other computer not sure where the creds are cached. I even deleted everything and started from scratch! still same issue on macOS. 
 
<img width="831" alt="image" src="https://github.com/user-attachments/assets/d2f9eaf4-65c9-47ae-b5be-d96009bb1d0b">

**Comment by IDKMANPLAYZ** [comment]
How do you use ollama api? How.

**Comment by merll002** [comment]
> How do you use ollama api? How.

What do you mean? It's in the instructions.
