### ISSUE TITLE
How to make AI chat another language

### ISSUE THREAD

**Issue by Dungsenpart** [kolbytn/mindcraft#154]
I want AI to chat in Vietnamese instead of English, can you help me?

**Comment by NobleSkye** [comment]
change the prompts to  Vietnamese, or at the start of each one say "here is your prompt but you must only reply in  Vietnamese" that should make it reply based on the AI model you are using

**Comment by FantomWolf182** [comment]
> using

I bet this would create a lot of errors with the code the Ai writes because it would bug out and also write the code in that language.

**Comment by FantomWolf182** [comment]
Honestly just easier for it to translate as I did in my PR so it can support many languages without changing prompts

**Comment by Dungsenpart** [comment]
what is PR that good?

**Comment by FantomWolf182** [comment]
PR means pull request. You can take a look here: [here](https://github.com/kolbytn/mindcraft/pull/165)

**Comment by FantomWolf182** [comment]
@Dungsenpart Hey there. Just wanted to inform you that the pull request has been merged and you can now change the bot's language in the settings file. Have fun!

**Comment by Dungsenpart** [comment]
thank you so much <3
