### ISSUE TITLE
Whats the name of directory

### ISSUE THREAD

**Issue by idkwhat-im-doing** [kolbytn/mindcraft#162]
I downloaded everything but cant find the right name of directory to run the npm install in please help

**Comment by saladnoob** [comment]
you run npm install in the project root. do you have node.js installed in your device?

**Comment by idkwhat-im-doing** [comment]
I have node.js, what's the project root?

**Comment by idkwhat-im-doing** [comment]
nevermind i forgot to actually use the node.js installer. Thanks!
