### ISSUE TITLE
Is a premium version of open Ai needed for this to work?

### ISSUE THREAD

**Issue by lacedapplefriter** [kolbytn/mindcraft#209]

**Comment by FantomWolf182** [comment]
Not the premium/plus version of open ai. What you need to run chatGPT as a model is access to they API which you do need to pay for after your inital free credit expires.

**Comment by lacedapplefriter** [comment]
@FantomWolf182 thanks, that's what I was thinking. Inside the code the error message gave me that it did not recognize the open Ai API key. So I assume it was not active
