### ISSUE TITLE
This mod needs the ability to memorize

### ISSUE THREAD

**Issue by DarkSpoderman** [kolbytn/mindcraft#251]
The last video made it clear that a missing memory is the biggest weakness when combining llms with the ability to play minecraft.

When previously experimenting with custom GPTs, i noticed that you can write coversation-history to and read from a text file, would it be possible to combine this with the mod?

**Comment by Shandelier** [comment]
you can use in context learning of LLMs for that. I would suggest creating a 1000 token memory space for model to write the effects of previous actions there. it would look like this:
```
...
33. attempted gathering wood -> obtained 2 oak wood
34. attempted gathering coal -> no coal near
35. attempted exit mine -> jump -> still the same height
36. attempted exit mine -> jump -> still the same height
37. attempted exit mine -> jump -> still the same height
```

**Comment by FantomWolf182** [comment]
Also note: mindcraft is not a mod.

**Comment by JurassikLizard** [comment]
You should probably close this issue
