### ISSUE TITLE
requiredIngedients[ingredientName] ??=0;

### ISSUE THREAD

**Issue by maltaja11** [kolbytn/mindcraft#254]
i have problems running main.js i used the npm  heres the log from vs code : PS C:\Users\Malte L\OneDrive\Desktop\mindcraft-main> node main.js
[ './andy.json' ]
file:///C:/Users/Malte%20L/OneDrive/Desktop/mindcraft-main/src/utils/mcdata.js:290
            requiredIngedients[ingredientName] ??=0;
                                               ^^^

SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.

**Comment by JurassikLizard** [comment]
What version is your node?

**Comment by maltaja11** [comment]
yes sorry i was on an old version

**Comment by JurassikLizard** [comment]
Do you mind closing this issue :)
