### ISSUE TITLE
"port" error

### ISSUE THREAD

**Issue by AlexeyBogomolov69** [kolbytn/mindcraft#262]
Node.js v20.18.0
PS C:\Users\Alexey\Desktop\mindcraft-main> node main.js
file:///C:/Users/Alexey/Desktop/mindcraft-main/settings.js:5
    "port": 55916,
    ^^^^^^

SyntaxError: Unexpected string
    at compileSourceTextModule (node:internal/modules/esm/utils:339:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
    at callTranslator (node:internal/modules/esm/loader:428:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:30)

**Comment by Lorodn4x** [comment]
We must open this port in Minecraft

**Comment by AlexeyBogomolov69** [comment]
I opened it via LAN and it doesn't work properly

**Comment by AlexeyBogomolov69** [comment]
I have a different time system (UTC+3) and therefore I will answer the next day at my place

**Comment by Lorodn4x** [comment]
ok, when I get home from work I'll try to help you

**Comment by Lorodn4x** [comment]
ok, when I get home from work I'll try to help you

**Comment by JurassikLizard** [comment]
Close this issue and ask someone on Discord. But the issue seems like your settings.js is broken, you should re-copy it from the repo.
