### ISSUE TITLE
Support for openrouter API

### ISSUE THREAD

**Issue by dwnmf** [kolbytn/mindcraft#264]
It would be really great if you add support for this api operator, as it allows to use most of llms available so far. openrouter.ai

**Comment by 1223nij** [comment]
https://openrouter.ai/docs/quick-start
in the docs there's an option for using openai's api
you can change `"model" : "blahblah"` in your profile.js to
```
"model": {
  "api": "openai",
  "url": "https://openrouter.ai/api/v1",
  "model": "????"
},
```

**Comment by dwnmf** [comment]
Thanks for response
