### ISSUE TITLE
error in the file loader.js

### ISSUE THREAD

**Issue by AlexeyBogomolov69** [kolbytn/mindcraft#266]
![2024-10-29_16-03-19](https://github.com/user-attachments/assets/ff526ba0-6473-4380-9b8f-5dafc881aafa)

**Comment by AlexeyBogomolov69** [comment]
![2024-10-29_16-11-34](https://github.com/user-attachments/assets/d7560919-583d-41d4-8fb6-8c64aac45988)

**Comment by JurassikLizard** [comment]
What version, and what client type are you using (vanilla, fabric, etc..)

**Comment by AlexeyBogomolov69** [comment]
vanilla
