### ISSUE TITLE
exit with code 0 on startup

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [kolbytn/mindcraft#291]
```
Using chat settings: { model: 'groq/llama-3.2-90b-vision-preview', api: 'groq' }
Using embedding settings: { api: 'groq' }
Unknown embedding:  groq . Using word overlap.
Logging in...
{}
Agent process exited with code 0 and signal null
```

```
[ './andy.json' ]
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
SES_UNHANDLED_REJECTION: {}
Agent process exited with code 0 and signal null
```

A few examples I've seen. I cannot reproduce. Logs are useless. SES_UNHANDLED_REJECTION is a recent module that might be responsible for it, but always triggers on error and I think is not the true issue.

**Comment by JurassikLizard** [comment]
https://github.com/endojs/endo/blob/master/packages/ses/error-codes/SES_UNHANDLED_REJECTION.md
here it says the error is due to a rejected promise that went unhandled, maybe something is interrupting the runtime?

**Comment by nimaid** [comment]
I am also having this issue, trying to use ollama.

**Comment by nimaid** [comment]
I have additioanlly tried this on Windows 10, with the same error.

Here is the output of `npm install`, in case it helps:
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported

> postinstall
> patch-package

patch-package 8.0.0
Applying patches...
mineflayer@4.20.1 ✔
mineflayer-collectblock@1.4.1 ✔
mineflayer-pathfinder@2.4.5 ✔
mineflayer-pvp@1.3.2 ✔

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    mineflayer@4.20.1

  applied to

    mineflayer@4.23.0

  At path

    node_modules/mineflayer

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package mineflayer

  to update the version in the patch file name and make this warning go away.

---
patch-package finished with 1 warning(s).

added 298 packages, and audited 299 packages in 5m

34 packages are looking for funding
  run `npm fund` for details

6 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
``

**Comment by erik-paula-origin** [comment]
The error still happening.

**Comment by Shadowcake59** [comment]
SES_UNHANDLED_REJECTION:


HELP

**Comment by rytina** [comment]
@MaxRobinsonTheGreat can this be solved locally through changing settings/platform or does this require a code change? Getting also this error on Ubuntu 24.10

`
node main.js
[ './andy.json' ]
MindServer running on port 8080
Client connected
Registering agents: andy
Agents registered
Starting agent with profile: ./andy.json
Starting agent initialization with profile: ./andy.json
Initializing action manager...
Initializing prompter...
Using chat settings: { model: 'gpt-4o', api: 'openai' }
Using embedding settings: { api: 'openai' }
Initializing history...
Initializing coder...
Initializing npc controller...
Initializing memory bank...
Initializing self prompter...
Initializing examples...
Examples initialized.
Initializing task...
andy logging into minecraft...
{}
Client connected
Connected to MindServer
Client disconnected
Agent process exited with code 0 and signal null
`
