### ISSUE TITLE
Keep Getting ECONNRESET Error when Running main.js

### ISSUE THREAD

**Issue by anti-integral** [kolbytn/mindcraft#300]
Hey, I keep getting this error after configuring everything and running main.js. Server is properly running on correct LAN port and wifi works. Any idea why?

`{ errno: -54, code: 'ECONNRESET', syscall: 'read' }`

full logs:
`$ node main.js
[ './andy.json' ]
Using chat settings: { model: 'claude-3-5-sonnet-20241022', api: 'anthropic' }
Using embedding settings: { api: 'anthropic' }
Unknown embedding:  anthropic . Using word overlap.
Logging into minecraft...
{}
{ errno: -54, code: 'ECONNRESET', syscall: 'read' }
Agent process exited with code 0 and signal null
✨  Done in 0.65s.`

**Comment by keneo** [comment]
looks like a network problem. firewall etc. can you connect to the same host port from from the same machine with anything else , i.e. with minecraft or telnet? also please show your settings.js
