### ISSUE TITLE
Ratelimits??

### ISSUE THREAD

**Issue by GH0STSecurity** [kolbytn/mindcraft#31]
for some reason this is sending too many requests before even joining the server, it does this until it gets a ratelimit error and then crashes and tries restarting which again, same thing happens :'((
```
RateLimitError: 429 Rate limit reached for text-embedding-ada-002 in organization org-n0dBBLrWyfW8gBN32Z8hu5N9 on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.
    at APIError.generate (file:///G:/Artificial_Intelilgence/mindcraft/node_modules/openai/error.mjs:58:20)
    at OpenAI.makeStatusError (file:///G:/Artificial_Intelilgence/mindcraft/node_modules/openai/core.mjs:256:25)
    at OpenAI.makeRequest (file:///G:/Artificial_Intelilgence/mindcraft/node_modules/openai/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GPT.embed (file:///G:/Artificial_Intelilgence/mindcraft/mindcraft/src/models/gpt.js:59:27)
    at async file:///G:/Artificial_Intelilgence/mindcraft/mindcraft/src/utils/examples.js:20:31
    at async Promise.all (index 13)
    at async Examples.load (file:///G:/Artificial_Intelilgence/mindcraft/mindcraft/src/utils/examples.js:23:25)
    at async Prompter.initExamples (file:///G:/Artificial_Intelilgence/mindcraft/mindcraft/src/agent/prompter.js:44:9)
    at async Agent.start (file:///G:/Artificial_Intelilgence/mindcraft/mindcraft/src/agent/agent.js:15:9) {
  status: 429
  ```
  What do i do???

**Comment by GH0STSecurity** [comment]
![image](https://github.com/kolbytn/mindcraft/assets/141128542/23312d06-70f6-4c54-9077-2e0949acafe8)
Some debugging incase yall can figure it out by this

**Comment by kolbytn** [comment]
This has to do with the rate limit set by your OpenAI account. It looks like you may need to add a payment method to your OpenAI account.

**Comment by GH0STSecurity** [comment]
> This has to do with the rate limit set by your OpenAI account. It looks like you may need to add a payment method to your OpenAI account.

@kolbytn why would i need a payment method? im using free credits and not planning on actually paying for the service ever, and doesnt this use gpt 3.5??? which part does it need embed text generation for? and is there not a way to add delay to the code to obey the rate limit?? cuz i can wait however long it takes, or is there not a way to just skip this part of the code or use gpt3.5 for it???

**Comment by kolbytn** [comment]
I'm not sure as I haven't tried using the free credits. Text embeddings are used to select which examples to include in the prompt when communicating with the bot.

**Comment by GH0STSecurity** [comment]
oh i see, well how do templates work? and does it have a big impact on the functionality of the code? like could i somehow skip that part, 
or maybe add delays in the code to stay in the ratelimit?
anyway for me to use this project or do i have to simply give up??

**Comment by homberger** [comment]
@GH0STSecurity: This is a great project and we should be thankful that it's shared with us. Please be a little less demanding.

**Comment by kolbytn** [comment]
> oh i see, well how do examples work? and does it have a big impact on the functionality of the code? like could i somehow skip that part,

You could try commenting out the use of `this.coding_examples` in [this](https://github.com/kolbytn/mindcraft/blob/main/src/agent/prompter.js) file.

**Comment by GH0STSecurity** [comment]
> @GH0STSecurity: This is a great project and we should be thankful that it's shared with us. Please be a little less demanding.

i have no doubt its a great project, im not demanding anything im just struggling to get it to work ;')

**Comment by GH0STSecurity** [comment]
> You could try commenting out the use of `this.coding_examples` in [this](https://github.com/kolbytn/mindcraft/blob/main/src/agent/prompter.js) file.

@kolbytn Have done that now aswell, still hitting ratelimits.
![image](https://github.com/kolbytn/mindcraft/assets/141128542/6b3f0300-1d58-4f87-9a58-cf37f7bed3d1)

somehow, like when i look at the usage tab i only see 1 api request per launch, but it says 3 used and 1 requested >> 
```on requests per min (RPM): Limit 3, Used 3, Requested 1. Please try again in 20s```

**Comment by IIIzP0III** [comment]
@GH0STSecurity 
this is unlikely a Issue in mindcraft but more a Issue inside your OpenAI account -
the ratelimit error appears too if you havent setup your OpenAI billing and organization options inside your OpenAI account correctly -

**Comment by kolbytn** [comment]
> somehow, like when i look at the usage tab i only see 1 api request per launch, but it says 3 used and 1 requested

Other api calls happen behind the scenes. We can't guarantee that our bot will work with free tier / credits, so I'm closing this issue for now.
