### ISSUE TITLE
ERRNO -4077 (groq/llama-3.2-90b-text-preview)

### ISSUE THREAD

**Issue by N0vaSs** [kolbytn/mindcraft#316]
![image](https://github.com/user-attachments/assets/a383ba5a-b54b-44f6-992f-ce127f8c48f8)

multiple apis used, no luck - also has problems finding api key in keys.json

used set "EXAMPLE_API=apikey" to fix this.

launches but error reproduces

**Comment by N0vaSs** [comment]
I’m addition to this another issue is that running node main.js never find keys.json

**Comment by Uncover-F** [comment]
Are you on the correct Minecraft version, if so have you opened the correct port? https://m.youtube.com/watch?v=gRotoL8P8D8

**Comment by N0vaSs** [comment]
> Are you on the correct Minecraft version, if so have you opened the correct port? https://m.youtube.com/watch?v=gRotoL8P8D8

Hey - I did take a look but found it was the wrong version, is there one that works for 1.20.1 or it 1.20.4 plus only?

**Comment by Uncover-F** [comment]
There is a way, but you have to modify some json files.

**Comment by N0vaSs** [comment]
> It’s currently supported to 1.21 or lower, but it has to be manually changed in settings.

Is it only in the settings.json - I changed a variable to 1.20.1 but that’s all I did.

**Comment by N0vaSs** [comment]
> Did you try that?

Yeah I changed just the version though. I’m using llama - idk if 1.20.1 works

**Comment by Uncover-F** [comment]
Maybe try to use 1.20.4 its most stable on that version.

**Comment by Uncover-F** [comment]
An particular reason you would like to you 1.20.1?

**Comment by N0vaSs** [comment]
> An particular reason you would like to you 1.20.1?

It’s for a modded world u fortunately. Saw some really cool to potential with some of the mods.

**Comment by N0vaSs** [comment]
> An particular reason you would like to you 1.20.1?

Is there a more specific error log I can provide you?

**Comment by Uncover-F** [comment]
Mindcraft does not have good mod compatibility unfortunately. I’ve come across other issues when the ai failed to join a server with mods or resource packs

**Comment by Uncover-F** [comment]
The devs are trying to fix this issue.

**Comment by N0vaSs** [comment]
> The devs are trying to fix this issue.

Damn that sucks, I kinda thought so. It makes sense considering I have over 300 plus distant horizons, shaders, create, ice & fire. Loads of magic mods ect.

**Comment by Uncover-F** [comment]
Yeah…
