### ISSUE TITLE
How to start AI with ollama

### ISSUE THREAD

**Issue by Wav3lonNights** [kolbytn/mindcraft#320]
Failed to start agent process: {
  message: 'Failed to initialize agent components: API key "QWEN_API_KEY" not found in keys.json or environment variables!',
  stack: 'Error: Failed to initialize agent components: API key "QWEN_API_KEY" not found in keys.json or environment variables!\n' +
    '  at Agent.start (file:///C:/Users/wav3lon/Desktop/mindcraft-main/src/agent/agent.js:43:23)\n' +
    '  at file:///C:/Users/wav3lon/Desktop/mindcraft-main/src/process/init-agent.js:48:21\n' +
    '  at file:///C:/Users/wav3lon/Desktop/mindcraft-main/src/process/init-agent.js:57:3\n' +
    '  at ModuleJob.run (node:internal/modules/esm/module_job:268:25)\n' +
    '  at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)\n' +
    '  at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)',
  error: {}
}
Agent process exited with code 1 and signal null

**Comment by koolara** [comment]
you`re using llm with "qwen"-naming in it, so it digging for qwen  api

**Comment by Shroototem** [comment]
Make sure you have your profile setup correctly with the api and model names.
ex.
```
    "model": {
        "api": "ollama",
        "model": "llama3.2"
    }
```
