### ISSUE TITLE
how to set up the file andy.json for Ollama?

### ISSUE THREAD

**Issue by AlexeyBogomolov69** [kolbytn/mindcraft#335]
![image](https://github.com/user-attachments/assets/d93e98d0-6b8a-4d34-961e-3b6595558198)

**Comment by AlexeyBogomolov69** [comment]
![image](https://github.com/user-attachments/assets/54a98818-7624-42b9-a702-738cf0cfbbc0)

**Comment by keneo** [comment]
Unfortunately Ollana is unsupported. Also Olena and Osama
