### ISSUE TITLE
Mineflayer physicTick event

### ISSUE THREAD

**Issue by MrKekner** [kolbytn/mindcraft#36]
I followed the tutorial and everything, signed up for chatgpt twice because i bought the wrong product the first time lol and finally made progress to this screen. Now im stuck and cannot get past this error, am i just dumb? how do i fix this.

![image_2024-04-05_180315671](https://github.com/kolbytn/mindcraft/assets/29075627/28ad13b1-2e84-4525-8fd8-a4c9cb8bb8e4)

P.S. amazing work, have not used it yet but i am looking forward to doing so.

**Comment by MrKekner** [comment]
just noticed, the P in physicsTick isnt capitalised and i think it wants me to correct that to PhysicsTick. But idk how......

**Comment by MrKekner** [comment]
So i changed settings "Auth" from offline to microsoft, it asked me to authenticate and so i did. now it just keeps spamming the same stuff on repeat. 
![image_2024-04-05_183302488](https://github.com/kolbytn/mindcraft/assets/29075627/cff52cee-576b-458d-98a7-0978ffeb4b09)

**Comment by kolbytn** [comment]
Try the solution here: https://github.com/kolbytn/mindcraft/issues/30#issuecomment-2036204299

**Comment by MrKekner** [comment]
> Try the solution here: [#30 (comment)](https://github.com/kolbytn/mindcraft/issues/30#issuecomment-2036204299)

Thank you for the fast reply! I understand the solution, however does this mean that the bot needs its own account to play?

**Comment by GH0STSecurity** [comment]
> > Try the solution here: [#30 (comment)](https://github.com/kolbytn/mindcraft/issues/30#issuecomment-2036204299)
> 
> Thank you for the fast reply! I understand the solution, however does this mean that the bot needs its own minecraft account to play?

for microsoft authentication yes, for offline mode no, btw i came accross the same error about physictick but it didnt cause any problem

**Comment by kolbytn** [comment]
The physicstick is an unrealted warning that is always there. If you are playing offline this should not be an issue.

**Comment by MrKekner** [comment]
Everytime i try to use the bot offline, i just receive the error  "Agent process exited with code 0 and signal null, the server i am hosting says the bots username failed to verify too. Is there something i am doing wrong? 

![image_2024-04-06_025011216](https://github.com/kolbytn/mindcraft/assets/29075627/56f93062-8331-44d1-941c-b406251cc18e)
![image_2024-04-06_025042317](https://github.com/kolbytn/mindcraft/assets/29075627/e1a392c8-d7b5-4ee8-a94d-866c2b821b08)

**Comment by homberger** [comment]
> Everytime i try to use the bot offline, i just receive the error "Agent process exited with code 0 and signal null,

Did you apply the patch mentioned on `npm install`? I had the same problem of "Agent process exited with code 0" and after applying the patch (`npx patch-package mineflayer`) it worked.

**Comment by jj142** [comment]
@homberger you seem to be familiar with setting up the AI bot could you give me a hand please im having the same issues Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead. If possible could you guide me via discord thank you! user:  Jjrockz
