### ISSUE TITLE
Client disconnected Agent process exited with code 0 and signal null

### ISSUE THREAD

**Issue by sadSmlie** [kolbytn/mindcraft#361]
The following problems always occur：
Examples initialized.
andy logging into minecraft...
Agent registered: andy
Client disconnected
Agent process exited with code 0 and signal null

**Comment by sadSmlie** [comment]
(node:25844) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Client connected
Connected to MindServer
Agent registered: andy
Client disconnected
Agent process exited with code 0 and signal null

**Comment by eusthace811** [comment]
Same issue, any help?

**Comment by Fireman122111** [comment]
Closed? What did you do, @sadSmlie ??
