### ISSUE TITLE
Feature request | using multiple api keys /  using custom api endpoint

### ISSUE THREAD

**Issue by GH0STSecurity** [kolbytn/mindcraft#37]
so i was testing this project and noticed theres alot of frequent ratelimits that leads to the AI being a incredibly slow, it is not necessary to implement as the code basicly works fine and people who have paid API access will experience no problems, but i imagine there's gonna be quite alot of people who will not be able to use this project because of the god damn rate limits :/
So i came up with 2 ideas/features that can potentially be very useful, and you guys could consider adding it when you have time for it.

firstly, the ability to use custom endpoints, theres quite alot of free chatgpt api endpoints that people could use to get higher ratelimits while having no cost, i don't think something like this is hard to add but since i have near to no experience in nodejs i didnt know how to do it myself ( or i wouldve done it myself )

alternatively, being able to add multiple openai api key to be used at the same time could double the ratelimit, (by switching API keys between each request ) but this doesnt seem quite fitting as you would need multiple accounts and im pretty sure that would be against the TOS, but yeah it'd still work

So yeah please consider implementing one of these features as im pretty certain itll help alot of people who are trying to test this project in the future ;))

**Comment by IIIzP0III** [comment]
@GH0STSecurity 
this is unlikely a Issue in mindcraft but more a Issue with your OpenAI account -
if the billing and organization options inside the OpenAI account are incorrect despite not hitting the usage limit the ratelimit error will appears too -
they changed something inside the account options recently and you have to configure it inside your OpenAI account to get rid of the error -

**Comment by GH0STSecurity** [comment]
@IIIzP0III did you even read what i wrote 😭 , i never said it talked about any "issue" this is a feature request. and thats not even what im talking about....  my point was completely different.

**Comment by kolbytn** [comment]
Your first solution may be possible, but the issue is that different models and APIs require different prompt formats. I'm closing this issue for now as it's low priority to make this work with free tier accounts / credits.

**Comment by GH0STSecurity** [comment]
i mean i dont see how a custom endpoint is gonna change anything? its literally the same model lets say gpt 3.5, but with a diffrent endpoint, so there wont be as much ratelimit, it has no downsides and just makes things better so people have the option to use a custom api endpoint if they dont have openai official api or a paid api tier and rather wanna use free apis

**Comment by kolbytn** [comment]
Please be patient as no one is working on this project full time. Community support is welcome, but many feature requests will not be met unless someone from the community takes the initiative to work on it.

For now, see related discussion [here](https://github.com/kolbytn/mindcraft/issues/29).
