### ISSUE TITLE
Does it support tlauncher?

### ISSUE THREAD

**Issue by RandomGuy-nobody** [kolbytn/mindcraft#373]
I want to know if it supports t launcher because minecraft is too expensive in the country i live.

**Comment by bob1323** [comment]
yes it does
![image](https://github.com/user-attachments/assets/5d9aa74e-eea0-46a5-a77d-f86755a3c611)

**Comment by RandomGuy-nobody** [comment]
thank you! but i cant get the CMD to work though, i explain the issue when i am home and can use my computer to get an error screen to display my issue!

**Comment by RandomGuy-nobody** [comment]
nvm i fixed it!!!! thank you!

**Comment by RandomGuy-nobody** [comment]
nvm i fixed it!!!! thank you!
