### ISSUE TITLE
How to play with more than 1 bot?

### ISSUE THREAD

**Issue by RandomGuy-nobody** [kolbytn/mindcraft#387]
How?

**Comment by yeroc5311** [comment]
(_screenshot is settings.js_)
![image](https://github.com/user-attachments/assets/c5d3836e-ff74-4e46-a9c5-d00a1f97697d)
Highlighted in red, you remove the "//" for any of the bots that you want to use. For example. Andy's line is a comment (//). Simply remove the "//" and then you are done. When you want to stop using that bot, just make it a comment again. (aka just "//" the line, like in the screenshot.) (**I am assuming that you have proper API keys in keys.json.**)
