### ISSUE TITLE
Any Way To Run GPT model locally

### ISSUE THREAD

**Issue by sussyboy123** [kolbytn/mindcraft#41]
i want to run mindcraft but i have problem with rate limit and i dont want to buy a tier account

**Comment by Defalting** [comment]
Second, it would be nice to use a local model for this.

**Comment by dallytaur** [comment]
#29 

under this  #issue this  have been in the works and look like to be soon implemented.

**Comment by sussyboy123** [comment]
> #29
> 
> under this #issue this have been in the works and look like to be soon implemented.

i had a hard time doing it and i got it working but the ai take more than 5 minutes to respond and when i asked to do something. he keep saying he cant

**Comment by dallytaur** [comment]
> > #29
> > under this #issue this have been in the works and look like to be soon implemented.
> 
> i had a hard time doing it and i got it working but the ai take more than 5 minutes to respond and when i asked to do something. he keep saying he cant + any recommended model for mindcraft?

what GPU do you have

i use a 4060 ti 16gb

not tested as of yet but the best thing to do would be to get a 7b model and load it in 4 bit mode

flemmingmiguel_MBX-7B-v3 is model ive been working with however this not the best as LLM moved past it

**Comment by sussyboy123** [comment]
> > > #29
> > > under this #issue this have been in the works and look like to be soon implemented.
> > 
> > 
> > i had a hard time doing it and i got it working but the ai take more than 5 minutes to respond and when i asked to do something. he keep saying he cant + any recommended model for mindcraft?
> 
> what GPU do you have
> 
> i use a 4060 ti 16gb
> 
> not tested as of yet but the best thing to do would be to get a 7b model and load it in 4 bit mode
> 
> flemmingmiguel_MBX-7B-v3 is model ive been working with however this not the best as LLM moved past it

RTX 3050 11 GB

**Comment by dallytaur** [comment]
you may have iusses then LLM are heavy to run idk how help you on such low end gear

**Comment by sussyboy123** [comment]
> you may have iusses then LLM are heavy to run idk how help you on such low end gear

well is there at least any way to run gpt or claude without having a paid account?

**Comment by dallytaur** [comment]
> > you may have iusses then LLM are heavy to run idk how help you on such low end gear
> 
> well is there at least any way to run gpt or claude without having a paid account?

easiest why is to buy  better gpu

if your willing to go all out a 4090 24gb is your best bet

low end a 4060 Ti 16 gb

**Comment by kolbytn** [comment]
Last I checked you only need to add $10 to your openai account which will probably last you 6+ months of moderate 3.5 turbo use.
