### ISSUE TITLE
Are there any plans to make сode updater?

### ISSUE THREAD

**Issue by Zapzatron** [kolbytn/mindcraft#48]
Are there any plans to make the bot check for a new version and be able to install it via cli or interface?

**Comment by kolbytn** [comment]
Updating is usually as simple as editing `settings.json`. There are no plans to try to do this automatically.

**Comment by Zapzatron** [comment]
Downloading an update is easy yes, I mean that there can be a system to check if there are new updates so that you don't have to check often if new commits have been added.

**Comment by kolbytn** [comment]
There is no method for automatically downloading updates to the bot. If you are using git, the command `git pull` would do an update.
