### ISSUE TITLE
bot does not follow instructions

### ISSUE THREAD

**Issue by Thathip** [kolbytn/mindcraft#56]
Bot does not follow instructions given in minecraft, sometimes even using unrelated commands

Log:

[Log.txt](https://github.com/kolbytn/mindcraft/files/15055963/Log.txt)
[andy.json](https://github.com/kolbytn/mindcraft/files/15055959/andy.json)
[settings.json](https://github.com/kolbytn/mindcraft/files/15055960/settings.json)

**Comment by kolbytn** [comment]
Can you give a few examples? It looks like you're using the default `gpt-3.5-turbo` is that correct?

**Comment by Thathip** [comment]
yes, that is true

**Comment by Thathip** [comment]
nvm it works now
