### ISSUE TITLE
How to make Ollama models work ?

### ISSUE THREAD

**Issue by Philipou** [kolbytn/mindcraft#60]
So i wanted to try this ai bot and after reading the readme, i decided to go for the ollama models because they are free.
I did everything but it says i need to set the api key as environment variable...
Is the Ollama thing still in development or i missed something ?
Thanks in advance !
-Philipou

**Comment by kolbytn** [comment]
set the `model` attribute in the bot profile json (e.g. `andy.json`) to the model you want to use (e.g. `llama3`).

**Comment by Philipou** [comment]
Ooh thank you it's not doing this error now but i get a different one, something with ports probably ? 
Ill send console log (by the way the port in settings.json is left at default 55916):
```
C:\Users\phili\Desktop\mindcraft-main>node main.js
Loading examples...
Failed to send Ollama request.
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Local.send (file:///C:/Users/phili/Desktop/mindcraft-main/src/models/local.js:47:25)
    at async Local.embed (file:///C:/Users/phili/Desktop/mindcraft-main/src/models/local.js:35:19)
    at async file:///C:/Users/phili/Desktop/mindcraft-main/src/utils/examples.js:20:31
    at async Promise.all (index 1)
    at async Examples.load (file:///C:/Users/phili/Desktop/mindcraft-main/src/utils/examples.js:23:25)
    at async Prompter.initExamples (file:///C:/Users/phili/Desktop/mindcraft-main/src/agent/prompter.js:45:9)
    at async Agent.start (file:///C:/Users/phili/Desktop/mindcraft-main/src/agent/agent.js:18:9) {
  cause: Error: connect ECONNREFUSED ::1:11434
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}
file:///C:/Users/phili/Desktop/mindcraft-main/src/models/local.js:36
        return res['embedding']
                  ^

TypeError: Cannot read properties of null (reading 'embedding')
    at Local.embed (file:///C:/Users/phili/Desktop/mindcraft-main/src/models/local.js:36:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/phili/Desktop/mindcraft-main/src/utils/examples.js:20:31
    at async Promise.all (index 1)
    at async Examples.load (file:///C:/Users/phili/Desktop/mindcraft-main/src/utils/examples.js:23:25)
    at async Prompter.initExamples (file:///C:/Users/phili/Desktop/mindcraft-main/src/agent/prompter.js:45:9)
    at async Agent.start (file:///C:/Users/phili/Desktop/mindcraft-main/src/agent/agent.js:18:9)

Node.js v18.16.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

C:\Users\phili\Desktop\mindcraft-main>
```
I saw port 11434 in the error message and tried opening minecraft lan to this port but it says this:
![Capture d’écran (279)](https://github.com/kolbytn/mindcraft/assets/71514309/7420326b-9d7f-4687-8fe6-002147d939c8)

(also i dont really know anything about javascript or node.js so sorry if this is a dumb question :)

**Comment by kolbytn** [comment]
The minecraft port number should match the port in the `settings.json` file. It should be `55916` by default. 

The port error shown above probably means that ollama is not running on your machine or the correct models have not been pulled yet. Use `ollama pull llama3` and `ollama pull nomic-embed-text` in your terminal.

**Comment by Philipou** [comment]
Will try tomorrow  but I think I did everything... 
Thank you for your help also and sorry for my bad English I'm from France

**Comment by Philipou** [comment]
Hello, i tried doing what you said and connecting to another wifi because it said this : ` cause: Error: connect ECONNREFUSED ::1:11434` but it did not work. I also tried restarting ollama but still nothing...

**Comment by jcobol** [comment]
> Hello, i tried doing what you said and connecting to another wifi because it said this : ` cause: Error: connect ECONNREFUSED ::1:11434` but it did not work. I also tried restarting ollama but still nothing...

Try pointing at `127.0.0.1` instead of `localhost`. The `::1:11434` looks like an ipv6 address which the localhost hosts entry on your machine might be pointing to, so using an ipv4 address will work around that.

**Comment by jcobol** [comment]
If you run `ollama list`, you should see some models listed.  You need a model like llama3 as well as nomic-embed-text.
```
C:> ollama list
NAME                                    ID              SIZE    MODIFIED
llama3:latest                           71a106a91016    4.7 GB  7 days ago
nomic-embed-text:latest                 0a109f422b47    274 MB  24 hours ago
```
Your settings.json should look like this:
```
{
    "minecraft_version": "1.20.1",
    "host": "127.0.0.1",
    "port": 55916,
    "auth": "offline",
    "allow_insecure_coding": false
}
```
And the start of andy.json should look like this:
```
{
    "name": "andy",
    "model": "llama3",
...
```
Start up Minecraft and be sure to run the version that matches what's in your settings.json.
Open to LAN and choose port 55916 to match settings.json.  If the version of Minecraft you choose doesn't allow setting the port, you'll have to see what port Minecraft chooses randomly and update that value into your settings.json.
Then start mindcraft with `node main.js`.

Hope that helps!

**Comment by Philipou** [comment]
Hey, i managed to fix it by changing local host to 127.0.0.1 in settings.json and doing the same in the `/src/models/local.js` file at line 5. 
Thank you very much for your help !
But now i have some trouble making it do things, it does repond to messages and sometimes do little actions like when i say come here but when i say something like mine 2 grass blocks it either just send a message or says "no code provided". I then tried to use the code block formatting in every possible way, with the //, without, with !newAction, without but it still wont do it, it says i didn't write code...

**Comment by jcobol** [comment]
> But now i have some trouble making it do things, it does repond to messages and sometimes do little
> actions like when i say come here but when i say something like mine 2 grass blocks it either just send a
> message or says "no code provided".

You can try setting "allow_insecure_coding" to true in your settings.json to allow mindcraft to write code.

Your experience may differ, but in my own trials generating code for Minecraft using a local model, I haven't had much success.
@kolbytn How about you?

**Comment by kolbytn** [comment]
The local models don't work as well. Llama3 sometimes works for me, but not consistently. It will probably require finetuning to get anything that small working well.

**Comment by Philipou** [comment]
Alright thanks !
