### ISSUE TITLE
Relogin to microsoft

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [kolbytn/mindcraft#64]
I am trying to log into my Alt account using the Microsoft authenticator. The json file has the name as the correct Minecraft account but the console is asking if it owns Minecraft. I have used this account with mindcraft a while back but now it's not working. How can I re log into the Microsoft account?

**Comment by MaxRobinsonTheGreat** [comment]
does it say something like `Profile not found`? I've seen this before when switching accounts. I had to go to `%AppData%\Roaming\.minecraft\nmp-cache` in file explorer and delete all the files there (windows).
