### ISSUE TITLE
Bot doesnt do what i want him to do (Ollama)

### ISSUE THREAD

**Issue by Luca-Girotti** [kolbytn/mindcraft#75]
I am currently using the Ollama bot, however it doesn't do anything. I dropped him so blocks, he picked them up, but when I tell him in chat to build something with them or to come where I am, he doesn't move and doesn't do anything.

Am I doing something wrong or am I perhaps using it in the wrong way?

**Comment by Luca-Girotti** [comment]
And also how are the commands like '!goToPlayer' actually work, since my bot doesn't really do what I am asking him to do maybe I should give him commands?

**Comment by Luca-Girotti** [comment]
example of logs:
Awaiting local response... (model: llama3)
Messages: [
  {
    role: 'system',
    content: "You are a playful Minecraft bot named andy that can converse with players, see, move, mine, build, and interact with the world by using commands. Act human-like as if you were a typical Minecraft player, rather than an AI. Be very brief in your responses, don't apologize constantly, don't give instructions or make lists unless asked, and don't refuse requests. Don't pretend to act, use commands immediately when requested. Do NOT say this: 'Sure, I've stopped.', instead say this: 'Sure, I'll stop. !stop'. Do NOT say this: 'On my way! Give me a moment.', instead say this: 'On my way! !goToPlayer('playername', 3)'. This is extremely important to me, take a deep breath and have fun :)\n" +
      '\n' +
      'STATS\n' +
      '- Position: x: 5.50, y: 107.00, z: -7.50\n' +
      '- Health: 20 / 20\n' +
      '- Hunger: 20 / 20\n' +
      '- Biome: plains\n' +
      '- Weather: clear\n' +
      '- Time: Night\n' +
      '- Other Players: Topo1717\n' +
      '\n' +
      '\n' +
      'INVENTORY\n' +
      '- oak_planks: 192\n' +
      '- acacia_planks: 64\n' +
      '- acacia_stairs: 64\n' +
      '- mangrove_planks: 64\n' +
      '- stripped_mangrove_log: 64\n' +
      '- mangrove_slab: 64\n' +
      '\n' +
      '\n' +
      '*COMMAND DOCS\n' +
      ' You can use the following commands to perform actions and get information about the world. \n' +
      '    Use the commands with the syntax: !commandName or !commandName("arg1", 1.2, ...) if the command takes arguments.\n' +
      '\n' +
      '    Do not use codeblocks. Only use one command in each response, trailing commands and comments will be ignored.\n' +
      "!stats: Get your bot's location, health, hunger, and time of day.\n" +
      "!inventory: Get your bot's inventory.\n" +
      '!nearbyBlocks: Get the blocks near the bot.\n' +
      "!craftable: Get the craftable items with the bot's inventory.\n" +
      '!entities: Get the nearby players and entities.\n' +
      '!modes: Get all available modes and see which are on/off.\n' +
      '!savedPlaces: List all saved locations.\n' +
      '!newAction: Perform new and unknown custom behaviors that are not available as a command by writing code.\n' +
      '!stop: Force stop all actions and commands that are currently executing.\n' +
      '!restart: Restart the agent process.\n' +
      '!clearChat: Clear the chat history.\n' +
      '!setMode: Set a mode to on or off. A mode is an automatic behavior that constantly checks and responds to the environment.\n' +
      'Params:\n' +
      'mode_name: (string) The name of the mode to enable.\n' +
      'on: (bool) Whether to enable or disable the mode.\n' +
      '!goToPlayer: Go to the given player.\n' +
      'Params:\n' +
      'player_name: (string) The name of the player to go to.\n' +
      'closeness: (number) How close to get to the player.\n' +
      '!followPlayer: Endlessly follow the given player. Will defend that player if self_defense mode is on.\n' +
      'Params:\n' +
      'player_name: (string) The name of the player to follow.\n' +
      'follow_dist: (number) The distance to follow from.\n' +
      '!moveAway: Move away from the current location in any direction by a given distance.\n' +
      'Params:\n' +
      'distance: (number) The distance to move away.\n' +
      '!rememberHere: Save the current location with a given name.\n' +
      'Params:\n' +
      'name: (string) The name to remember the location as.\n' +
      '!goToPlace: Go to a saved location.\n' +
      'Params:\n' +
      'name: (string) The name of the location to go to.\n' +
      '!givePlayer: Give the specified item to the given player.\n' +
      'Params:\n' +
      'player_name: (string) The name of the player to give the item to.\n' +
      'item_name: (string) The name of the item to give.\n' +
      'num: (number) The number of items to give.\n' +
      '!collectBlocks: Collect the nearest blocks of a given type.\n' +
      'Params:\n' +
      'type: (string) The block type to collect.\n' +
      'num: (number) The number of blocks to collect.\n' +
      '!collectAllBlocks: Collect all the nearest blocks of a given type until told to stop.\n' +
      'Params:\n' +
      'type: (string) The block type to collect.\n' +
      '!craftRecipe: Craft the given recipe a given number of times.\n' +
      'Params:\n' +
      'recipe_name: (string) The name of the output item to craft.\n' +
      'num: (number) The number of times to craft the recipe. This is NOT the number of output items, as it may craft many more items depending on the recipe.\n' +
      '!smeltItem: Smelt the given item the given number of times.\n' +
      'Params:\n' +
      'item_name: (string) The name of the input item to smelt.\n' +
      'num: (number) The number of times to smelt the item.\n' +
      '!placeHere: Place a given block in the current location. Do NOT use to build structures, only use for single blocks/torches.\n' +
      'Params:\n' +
      'type: (string) The block type to place.\n' +
      '!attack: Attack and kill the nearest entity of a given type.\n' +
      'Params:\n' +
      'type: (string) The type of entity to attack.\n' +
      '!goToBed: Go to the nearest bed and sleep.\n' +
      '!activate: Activate the nearest object of a given type.\n' +
      'Params:\n' +
      'type: (string) The type of object to activate.\n' +
      '!stay: Stay in the current location no matter what. Pauses all modes.\n' +
      '!goal: Set a goal to automatically work towards.\n' +
      'Params:\n' +
      'name: (string) The name of the goal to set. Can be item or building name. If empty will automatically choose a goal.\n' +
      'quantity: (number) The quantity of the goal to set. Default is 1.\n' +
      '*\n' +
      '\n' +
      'Examples of how to respond:\n' +
      'Example 1:\n' +
      'User input: zZZn98: come here\n' +
      'Your output:\n' +
      "On my way! !goToPlayer('zZZn98', 3)\n" +
      'System output: Arrived at player.\n' +
      'Your output:\n' +
      'Here!\n' +
      'User input: zZZn98: no come right where I am\n' +
      'Your output:\n' +
      "Okay, I'll come right to you. !goToPlayer('zZZn98', 0)\n" +
      '\n' +
      'Example 2:\n' +
      'User input: hanky: kill that zombie!\n' +
      'Your output:\n' +
      "I'm attacking! !attack('zombie')\n" +
      'System output: Code Output:\n' +
      'No zombie nearby\n' +
      'Your output:\n' +
      'I could not find a zombie nearby.\n' +
      '\n' +
      '\n' +
      'Conversation Begin:'
  },
  {
    role: 'system',
    content: 'Agent process restarted. Notify the user and decide what to do.'
  }
]
received message from Topo1717 : build a house
received message from Topo1717 : build something

**Comment by BorbTheBird** [comment]
heres what i said in a different post: https://github.com/kolbytn/mindcraft/issues/71#issuecomment-2102063737

**Comment by kolbytn** [comment]
See the conversation in #71
