### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by Zapzatron** [kolbytn/mindcraft#80]
![image](https://github.com/kolbytn/mindcraft/assets/100136305/48ff15d8-85f0-43bb-96c5-17e0723ee35b)

**Comment by AuXFire** [comment]
This could be a mineflayer thing but it looks like to me there is no check in place for knowing if the player is alive before running that function. You could implement that and see how it goes.

**Comment by JGsouzaa** [comment]
I think this could be a bug when the agent player is dead, you need to write on code a checker if the agent exists so you can check his name (If someone can implement this before me).

I think a better solution is via interfacing this modes and them instanciating when the agent is alive, but for now if it's not that criticall it could be enough to just check if the agent exists.

Could you please give more context or detail about this problem? If this error throws when you tried to give some command via chat or if this occur in other situation?

**Comment by kolbytn** [comment]
See https://github.com/kolbytn/mindcraft/pull/83

**Comment by kolbytn** [comment]
Should be fixed. Feel free to reopen if issue persists.
