### ISSUE TITLE
Support 1.20.6

### ISSUE THREAD

**Issue by TrevorJTClarke** [kolbytn/mindcraft#84]
Whats required to update the release support? Happy to help if you need

**Comment by kolbytn** [comment]
It's dependent on what the [mineflayer repo](https://github.com/PrismarineJS/mineflayer) supports. Which right now is only 1.20.4

**Comment by TrevorJTClarke** [comment]
gotcha - ive added a PR there https://github.com/PrismarineJS/node-minecraft-protocol/pull/1301
