### ISSUE TITLE
Any plans for a "record my actions" mode?

### ISSUE THREAD

**Issue by TrevorJTClarke** [kolbytn/mindcraft#85]
Been playing around with this a lot, and seems like the prompting is great and all but what I want is repetitive actions to get done based on how I show/catalog actions to an NPC. Think of a prompt session like this:
```
Follow me and record the actions i take starting now. I will tell you when to stop recording the actions i take. Watch what I do and lets call it sorterArray. 

(i place a bunch of blocks)

Stop recording. List the items needed to complete 1 sorterArray
```

Thoughts on this? Feels like a natural progression of newAction where it could rely on memory feedback and store executable code.

**Comment by TrevorJTClarke** [comment]
also just wanna say - awesome work so far - its epic stuff

**Comment by kolbytn** [comment]
We unfortunately do not have any way of recording a user's actions directly. Although we could record how the blocks in the world change... 

We have been considering other ways the bot can teach itself new commands using feedback from the user, but we don't have any plans to implement this in the near future.
