### ISSUE TITLE
I still dont understand on how to add an enviroment table

### ISSUE THREAD

**Issue by Edcaaaa4gy53** [kolbytn/mindcraft#87]
Like i dont know how to name the variable, nor anything??? And when i name it as "GEMINI_API_KEY=(my private key)", when i add it to all of them, i notice that it just overwrite and only set to the last one! what the hell is this, i need quick help

**Comment by Edcaaaa4gy53** [comment]
i swear to god bruh what is this, i need quick help

**Comment by Edcaaaa4gy53** [comment]
i need quick help bruh

**Comment by kolbytn** [comment]
What OS are you using. What are you using to launch mindcraft?

**Comment by Edcaaaa4gy53** [comment]
> What OS are you using. What are you using to launch mindcraft?

Windows. i followed the instructions

**Comment by Edcaaaa4gy53** [comment]
this is the worst support ive ever got

**Comment by kolbytn** [comment]
In Windows, if you are using powershell, you can set environment variables like this: `$env:OPENAI_API_KEY="your-key"`

More info [here](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.4#use-the-variable-syntax).

**Comment by Edcaaaa4gy53** [comment]
is the gemini the same?? also where do set them???

**Comment by kolbytn** [comment]
Yes, but if you pull from main we just added support for using a keys.json file to store your keys in plain text instead. Instructions are in the updated readme.
