### ISSUE TITLE
Bot only says Hello

### ISSUE THREAD

**Issue by jkramer5103** [kolbytn/mindcraft#92]
Hello, i can load the bot into the world perfectly, but if i speak to him to mine some sand, he only says stuff like hi, im andy, a friendly Mc bot, here is the command line output: [https://pastebin.com/kYsKQRS1](https://pastebin.com/kYsKQRS1)
to install, i only git cloned the package, ran npm install and then node main.js (i had my openai key as environment variable saved) and it's also requesting API Keys.

**Comment by kolbytn** [comment]
Very odd. I haven't seen this before. It looks like none of you messages are being saved in it's history and it's repeatedly replying to the initialization message. Can you confirm that this is still happening and what username the bot it using? Maybe try redoing the repo setup completely.

**Comment by supermiguelon2019** [comment]
it also happens with ollama

**Comment by supermiguelon2019** [comment]
I think what happens is that it does not receive the content of the messages from the players, because it does receive the server messages like changing the time.

**Comment by jkramer5103** [comment]
Maybe

**Comment by supermiguelon2019** [comment]
I found the bug for my problem, I was using the Fabulously Optimized modpack and it was making the AI unable to read the messages, maybe the No Chat Reports mod was causing it.

**Comment by jkramer5103** [comment]
I didnt tested it out already but its probably Right, I used Simply optimized.
