### ISSUE TITLE
Free model

### ISSUE THREAD

**Issue by gryhfgyd** [kolbytn/mindcraft#94]
Hello everyone!!! I would like to see a free model that I don't have to pay for.... Can anyone make it? I'm not really good at coding, and I can't even find a free alternative to ebedding.

**Comment by kolbytn** [comment]
Use the instructions for ollama in the README. Ollama has given some people trouble, and we're working to fix that. Also, the model will not work as well as the paid models, and there's nothing we can do about that now.
